;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="GameplayCue.InstaKill1",NewTagName="GameplayCue.InstaKill")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Gameplay.AniNotify.CastEnd",DevComment="")
+GameplayTagList=(Tag="Gameplay.Element.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Explosion",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.GA.FireBall_Damage",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.GE.Burning",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.GE.SetByCaller.BurningTime",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.GE.SetByCaller.Health",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AnimationNotify.CastEnd",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Burning",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Explosion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.InstaKill",DevComment="")

